---
title: Model Fitting on Abortion Rates
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)


# calling helper file that reads in all models, packages, data, and homemade functions

source('model-helpers/model_helper_lme.R')
  

# loading packages & map data here since that's not specifically for modeling &
# this may move to another script eventually

{
  library(maps)
  states <- map_data('state')
  map_df <- usa@data %>% 
    mutate(NAME_1 = str_to_lower(NAME_1)) %>% 
    inner_join(states, by = c('NAME_1' = 'region'))
}

# defining functions that I will call later on

{
  
  # extracting a summary dataframe for my nlme models
  
  get_lme_summary_df <- function(mod) {
    return(clean_names(rownames_to_column(as.data.frame(summary(mod)$tTable), 'term')))
  }
  
  # writing a function to get the summary df object for my SAR models

  get_sar_summary_df <- function(sar_mod) {
    unclass(summary(sar_mod))$Coef %>% 
      as.data.frame() %>% 
      rownames_to_column('term') %>% 
      clean_names() %>% 
      rename(value = estimate,
             p_value = pr_z)
  }
}

```

## Testing for Spatial Autocorrelation

```{r maps}

# producing 2010 vs 2019 plots for each of our 3 response variables

p1 <- map_df %>% 
  filter(year %in% c(2010, 2019)) %>% 
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = abortion_per_1k_births),
               color = 'black') +
  scale_fill_gradient2(high = 'red3') +
  coord_fixed(1.2) +
  facet_wrap(~year) +
  labs(title = 'Abortion Rate',
       fill = '') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

# nonres rate

p2 <- map_df %>% 
  filter(year %in% c(2010, 2019)) %>% 
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = rate_nonres),
               color = 'black') +
  scale_fill_gradient2(high = 'red3') +
  coord_fixed(1.2) +
  facet_wrap(~year) +
  labs(title = 'Nonresident Abortion Rate',
       fill = '') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

# late rate

p3 <- map_df %>% 
  filter(year %in% c(2010, 2019)) %>% 
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = rate_late),
               color = 'black') +
  scale_fill_gradient2(high = 'red3') +
  coord_fixed(1.2) +
  facet_wrap(~year) +
  labs(title = 'Later-term Abortion Rate',
       fill = '') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

# putting plots together

ggarrange(p1, p2, p3, nrow = 3) %>% 
  annotate_figure(top = text_grob('Spatial structure in outcome variables', 
                                  size = 14))

```

```{r global_morans}

# extracting model weight & preparing listws for moran tests

cor_mats <- as.matrix(Initialize(cor_structs[[2]], data = usa@data))
listws <- lapply(cor_mats, mat2listw)
global_moran_results <- list()
m <- 1

# iterating through the variables

for (outcome in list(usa@data$abortion_per_1k_births,
                     usa@data$rate_nonres,
                     usa@data$rate_res,
                     usa@data$rate_late,
                     usa@data$rate_early,
                     usa@data$prop_late)) {
  
  # iterating through each year for each model
  
  for (i in 1:length(2010:2019)) {
  
    # getting the residuals for the current year
    
    this_year <- c(2010:2019)[i]
    this_listw <- listws[[i]]
    this_outcome <- outcome[usa@data$year == this_year]
    
    # now running the moran test
    
    global_moran_results[[m]] <- moran.mc(this_outcome, 
                                   this_listw,
                                   alternative = 'two.sided',
                                   nsim = 9999)
    m <- m+1
  }
}

# putting Moran results in a nice table

moran_outcomes <- do.call(rbind, lapply(global_moran_results, tidy)) %>% 
  mutate(year = rep(2010:2019, times = 6),
         var = rep(c('rate', 'rate_nonres', 'rate_res',
                     'rate_late', 'rate_early', 'prop_late'), each = 10),
         significant = p.value < 0.05) 
moran_outcomes %>% 
  select(year, statistic, p.value) %>% 
  mutate(across(statistic:p.value, function(x) round(x, 3))) %>% 
  kable(booktabs = TRUE,
        #format = 'latex',
        col.names = c('Year', 'I-statistic', 'p-value'),
        caption = "Moran's I-test on outcome variables") %>% 
  pack_rows('Abortion rates', 1, 10) %>%
  pack_rows('Nonresident abortion rate', 11, 20) %>% 
  pack_rows('Resident abortion rate', 21, 30) %>%
  pack_rows('Later-term abortion rate', 31, 41) %>%  
  pack_rows('Earlier-term abortion rate', 41, 50) %>% 
  pack_rows('Later-term abortion rate', 51, 60) %>% 
  column_spec(1:3, width = "7em") 

```

```{r distributions}

# I want to plot all of the dependent variables & their respective
# transformations to Gaussian

{
  # this requires some data manipulation, which I'm doing below
  
  untransformed <- usa@data %>% 
    select(abortion_per_1k_births,
           rate_nonres,
           rate_res,
           rate_late,
           rate_early,
           prop_late) %>% 
    pivot_longer(everything()) %>% 
    mutate(transformed = FALSE,
           transformation = case_when(name == 'abortion_per_1k_births' ~ 'sqrt(y)',
                                      name == 'rate_nonres' ~ 'log(y)',
                                      name == 'rate_res' ~ 'sqrt(y)',
                                      name == 'rate_late' ~ 'sqrt(y)',
                                      name == 'rate_early' ~ 'sqrt(y)',
                                      name == 'prop_late' ~ 'sqrt(y)')) 
  
  graph_df <- untransformed %>% 
    mutate(value = case_when(name == 'abortion_per_1k_births' ~ sqrt(value),
                             name == 'rate_nonres' ~ log(value),
                             name == 'rate_res' ~ sqrt(value),
                             name == 'rate_late' ~ sqrt(value),
                             name == 'rate_early' ~ sqrt(value),
                             name == 'prop_late' ~ sqrt(value)),
           transformed = TRUE) %>% 
    bind_rows(untransformed) %>% 
    mutate(transformation = ifelse(transformed, transformation, 'y')) 
  
  # creating a list of plots in a loop to streamline the code
  
  plots <- list()
  dep_vars <- c('abortion_per_1k_births', 'rate_nonres', 'rate_res',
                'rate_late', 'rate_early', 'prop_late')
  facet_labels <- c('Overall Abortion Rate', 'Nonresident Abortion Rate', 'Resident Abortion Rate',
                    'Later-Term Abortion Rate', 'Earlier-Term Abortion Rate', 'Later-Term Share of Abortions')
  for (i in 1:length(dep_vars)) {
    plots[[i]] <- graph_df %>% 
      filter(name == dep_vars[i]) %>% 
      mutate(transformation = fct_relevel(transformation, 'y')) %>% 
      ggplot(aes(value)) +
      geom_histogram() +
      facet_wrap(~transformation, scales = 'free') +
      labs(title = facet_labels[[i]], x = '', y = '') +
      theme_thesis()
  }
  
  # printing out the plots
  
  grid1 <- ggarrange(plots[[1]], plots[[2]], plots[[3]],
            nrow = 3) 
  grid2 <- ggarrange(plots[[4]], plots[[5]], plots[[6]],
                     nrow = 3)
  ggarrange(grid1, grid2) %>% 
    annotate_figure(left = text_grob('Count', rot = 90, vjust = 1, family = 'Times'),
                    bottom = text_grob('Value', family = 'Times')) 

  ggsave('figures/eda/transform_dists.png', width = 10, height = 7)
}


# also creating a histogram of standardized scores for EDA

usa@data %>% 
  select(within_score, surrounding_score) %>% 
  pivot_longer(everything()) %>% 
  mutate(name = str_to_title(str_replace_all(name, '_', '-State ' ))) %>% 
  mutate(name = fct_relevel(name, 'Within-State Score', 'Surrounding-State Score')) %>% 
  ggplot(aes(value)) +
  geom_histogram() +
  # geom_vline(xintercept = 0) +
  # geom_vline(xintercept = 1, linetype = 'dashed', color = 'red') +
  # geom_vline(xintercept = -1, linetype = 'dashed', color = 'red') +
  # geom_vline(xintercept = 2, linetype = 'dotted', color = 'red') +
  # geom_vline(xintercept = -2, linetype = 'dotted', color = 'red') +
  facet_wrap(~name) +
  theme_thesis() +
  labs(x = 'Standardized Policy Score',
       y = 'Count')
ggsave('figures/eda/std_score_hist.png',
       width = 7, height = 3)

# I also want a quick table of standardized examples

ep <- 0.05
usa@data %>% 
  filter(within_score > -2-ep & within_score < -2+ep) %>% 
  select(NAME_1, year, within_score)

```

## Examining models

```{r model_comparison}

# running an LRT between the LME and LME with autocorrelation for each of the variables

i <- 1
anova(fitted_models$rate$raw$all_mods$none, fitted_models$rate$raw$all_mods$gaus) %>% 
  bind_rows(anova(fitted_models$rate_nonres$raw$all_mods$none, fitted_models$rate_nonres$raw$all_mods$gaus)) %>% 
  bind_rows(anova(fitted_models$rate_res$raw$all_mods$none, fitted_models$rate_res$raw$all_mods$gaus)) %>% 
  bind_rows(anova(fitted_models$rate_late$raw$all_mods$none, fitted_models$rate_late$raw$all_mods$gaus)) %>% 
  bind_rows(anova(fitted_models$rate_early$raw$all_mods$none, fitted_models$rate_early$raw$all_mods$gaus)) %>% 
  bind_rows(anova(fitted_models$prop_late$raw$all_mods$none, fitted_models$prop_late$raw$all_mods$gaus)) %>%
  as_tibble() %>% 
  mutate(` ` = rep(c('Nonspatial', 'Spatial'), times = 6)) %>% 
  select(-c(call, Model)) %>% 
  select(` `, everything()) %>% 
  mutate(across(c(AIC:logLik, L.Ratio), function(x) round(x, 1))) %>%
  mutate(`p-value` = round(`p-value`, 3)) %>% 
  select(-L.Ratio) %>% 
  kable(booktabs = TRUE,
        caption = 'Likelihood Ratio Tests do not support the use of spatial models',
        # format = 'latex',
        align=c(rep('c', times = 7))) %>% 
  column_spec(1:7, width = "4em") %>% 
  pack_rows('Abortion Rate (abortions per 1k live births)', 1, 2) %>% 
  pack_rows('Nonresident Abortion Rate', 3, 4) %>% 
  pack_rows('Resident Abortion Rate', 5, 6) %>% 
  pack_rows('Later-term Abortion Rate', 7, 8) %>% 
  pack_rows('Earlier-term Abortion Rate', 9, 10) %>% 
  pack_rows('Later-term Share of Abortions', 11, 12) 
# %>% 
#   row_spec(seq(1, 12, by = 2), bold = T, color = "black", background = "lightyellow")

```

```{r rate_coefs}

# naming columns for table

rate_colnames <- c(
  'Variable',
  'Overall rate model: Change in the square root of the abortion rate',
  'Nonresident rate model: Change in the natural log of the nonresident abortion rate',
  'Resident rate model: Change in the square root of the resident abortion rate'
)

# formatting overall, nonresident, and resident rate models

display_rate_df <- mutate(get_lme_summary_df(rate_mod), dep = 'rate') %>% 
  bind_rows(mutate(get_lme_summary_df(rate_nonres_mod), dep = 'nonres'),
            mutate(get_lme_summary_df(rate_res_mod), dep = 'res')) 
display_rate_df %>% 
  mutate(ci = paste0('(', round(value-qnorm(0.975)*std_error, 3), 
                     ', ', round(value+qnorm(0.975)*std_error, 3), ')'),
         value = round(value, 3)) %>% 
  mutate(value = ifelse(p_value < 0.05, paste0(value, '*'), value),
         # value = paste(value, ci),
         pr_z = round(p_value, 3)) %>% 
  select(term, value, dep) %>% 
  pivot_wider(names_from = dep, values_from = value) %>% 
  mutate(term = str_remove_all(term, 'within_between')) %>% 
  mutate(term = fct_relevel(term,
                            '(Intercept)',
                            'surrounding_score', 
                            'within_score', 
                            'surrounding_score:within_score',
                            'abortions', 'dem_2party', 'hh_income', 'pct_bachelors',
                            'prop_hisp', 'prop_nonwhite')) %>% 
  arrange(term) %>% 
  kable(booktabs = TRUE,
        #format = 'latex',
        col.names = c('Variable', 'Overall Rates', 'Nonresident Rates', 'Resident Rates'),
        caption = 'Fixed-Effects Coefficients for Linear Mixed-Effects Transformed Rate Models',
        align = c('l', rep('c', times = 3))) %>% 
  pack_rows('Policy environment', 2, 4) %>%
  pack_rows('Control variables', 5, 10)  %>% 
  # row_spec(c(2, 4), bold = T, color = "black", background = "lightyellow") %>%
  column_spec(1, width = "15em") %>% 
  column_spec(2:4, width = '5em')

```

```{r timing_coefs}

# creating a vector of column names again

time_colnames <- c(
  'Variable',
  'Later-term rate model: Change in the square root of the later-term abortion rate',
  'Earlier-term rate model: Change in the square root of the earlier-term abortion rate',
  'Later-term share model: Change in the square root of the later-term share of abortions'
)

# formatting a table as done above

display_timing_df <- bind_rows(mutate(get_lme_summary_df(rate_mod), dep = 'rate') %>% 
    mutate(get_lme_summary_df(rate_late_mod), dep = 'late_rate'),
    mutate(get_lme_summary_df(rate_early_mod), dep = 'early_rate'),
    mutate(get_lme_summary_df(prop_late_mod), dep = 'late_share'))
display_timing_df %>% 
  mutate(ci = paste0('(', round(value-qnorm(0.975)*std_error, 3), 
                     ', ', round(value+qnorm(0.975)*std_error, 3), ')'),
         value = round(value, 3)) %>% 
  mutate(value = ifelse(p_value < 0.05, paste0(value, '*'), value),
         # value = paste(value, ci),
         pr_z = round(p_value, 3)) %>% 
  select(term, value, dep) %>% 
  pivot_wider(names_from = dep, values_from = value) %>% 
  mutate(term = str_remove_all(term, 'within_between')) %>% 
  mutate(term = fct_relevel(term,
                            '(Intercept)',
                            'surrounding_score', 
                            'within_score', 
                            'surrounding_score:within_score',
                            'abortions', 'dem_2party', 'hh_income', 'pct_bachelors',
                            'prop_hisp', 'prop_nonwhite')) %>% 
  arrange(term) %>% 
  kable(booktabs = TRUE,
        #format = 'latex',
        col.names = c('Variable', 'Later-Term Rates', 'Earlier-Term Rates', 'Later-Term Share'),
        caption = 'Fixed-Effects Coefficients for Linear Mixed-Effects Transformed Timing Models',
        align = c('l', rep('c', times = 3))) %>% 
  pack_rows('Policy environment', 2, 4) %>%
  pack_rows('Control variables', 5, 10)  %>% 
  # row_spec(c(2, 4), bold = T, color = "black", background = "lightyellow") %>%
  column_spec(1, width = "15em") %>% 
  column_spec(2:4, width = '5em')

```

```{r isolate_policy_coefs}

# getting all score coefficients together, and then I will want to isolate by
# coefficient type

all_score_coefs <- display_rate_df %>% 
  bind_rows(display_timing_df) %>% 
  filter(str_detect(term, 'score')) %>% 
  select(dep, term, value, p_value) %>% 
  mutate(dep = case_when(dep == 'rate' ~ 'Overall abortion rates',
                         dep == 'nonres' ~ 'Nonresident abortion rates',
                         dep == 'res' ~ 'Resident abortion rates',
                         dep == 'late_rate' ~ 'Later-term abortion rates',
                         dep == 'early_rate' ~ 'Earlier-term abortion rates',
                         dep == 'late_share' ~ 'Later-term share of abortions')) %>% 
  mutate(change = ifelse(value < 0, 'Decrease', 'Increase'))

# writing a function to isolate specific score coefficient across all variables

display_policy_effects <- function (input) {
  title <- case_when(str_detect(input, ':') ~ 'Interaction',
          str_detect(input, 'surrounding') ~ 'Surrounding-state',
          str_detect(input, 'within') ~ 'Within-state')
  all_score_coefs %>% 
    filter(term == input) %>% 
    select(dep, change, value, p_value) %>% 
    mutate(value = round(value, 5),
           change = ifelse(p_value < 0.05, paste0(change, fixed('*')), change)) %>% 
    kable(booktabs = T,
          caption = paste(title, 'coefficients'),
          col.names = c('Transformed outcome', 'Change', 'Coefficient', 'p-value')) %>% 
    column_spec(2:3, width = '5em') %>% 
    kable_styling()
}

display_policy_effects('surrounding_score')
display_policy_effects('within_score')
display_policy_effects('surrounding_score:within_score')

```

```{r predict_change}

# creating dummy table where all predictors are average, except for surrounding_score

dummy_scores <- seq(-1, 1, by = 0.1)
dummy_df <- tibble(surrounding_score = rep(dummy_scores, times = 3),
                   within_score = rep(seq(-1, 1), each = length(dummy_scores)),
                   prop_bachelors = 0,
                   prop_hisp = 0,
                   prop_nonwhite = 0,
                   hh_income = 0,
                   dem_2party = 0,
                   total_population = 0,
                   year = 2019)

# adding predictions to this table & getting some other variables of interest

pred_diff_df <- dummy_df %>% 
  select(within_score, surrounding_score) %>% 
  mutate(rate = predict(rate_mod, dummy_df)^2,
         rate_nonres = exp(predict(rate_nonres_mod, dummy_df)),
         rate_res = predict(rate_res_mod, dummy_df)^2,
         rate_late = predict(rate_late_mod, dummy_df)^2,
         rate_early = predict(rate_early_mod, dummy_df)^2,
         prop_late = predict(prop_late_mod, dummy_df)^2) %>% 
  pivot_longer(rate:prop_late, names_to = 'outcome') %>% 
  mutate(outcome = fct_relevel(outcome, 
                               'rate', 'rate_nonres', 'rate_res',
                               'rate_late', 'rate_early', 'prop_late')) %>% 
  arrange(outcome) %>% 
  mutate(outcome = recode(outcome,
                           'rate' = 'Abortions per \n1000 live births',
                           'rate_nonres' = 'Nonresident abortions per \n1000 live births',
                           'rate_res' = 'Resident abortions per \n1000 live births',
                           'rate_late' = 'Later-term abortions per \n1000 live births',
                           'rate_early' = 'Earlier-term abortions per \n1000 live births',
                           'prop_late' = 'Later-term share of \nabortions')) 

# visualizing all outcomes together

pred_diff_df %>% 
  ggplot(aes(surrounding_score, value, color = as.factor(within_score))) +
  geom_line() +
  facet_wrap(~outcome, scales = 'free') +
  theme_thesis() +
  labs(x = 'Standardized Surrounding-State Score',
       y = 'Estimated Response',
       color = 'Standardized \nwithin-state \nscore') +
    scale_color_brewer(palette = 'OrRd')
ggsave('figures/eda/all_synthetic.png',
       width = 7, height = 4)

# outputting a df so I can see what the actual increases are when switching from
# -1 to 1 surrounding-state

pred_diff_df %>% 
  filter(within_score == 1, surrounding_score %in% c(-1, 1)) %>% 
  group_by(outcome) %>% 
  mutate(diff = value - lag(value))

```

```{r extra_synthetic_plots}

# getting each one separately

outcomes <- unique(pred_diff_df$outcome)
get_pred_plot <- function(x) {
  pred_diff_df %>% 
    filter(outcome == x) %>% 
    ggplot(aes(surrounding_score, value, color = as.factor(within_score))) +
    geom_line() +
    theme_thesis() +
    labs(x = 'Standardized surrounding-state score',
         y = x,
         color = 'Standardized \nwithin-state \nscore') +
      scale_color_brewer(palette = 'OrRd')
}
lapply(outcomes, get_pred_plot)

# illustrating why I only consider scores between -1 and 1

usa@data %>% 
  ggplot(aes(within_score, surrounding_score)) +
  geom_point() +
  theme_thesis() +
  geom_smooth(method = 'lm')

usa@data %>% 
  ggplot(aes(within_score, surrounding_score)) +
  geom_point() +
  theme_thesis() +
  geom_smooth(method = 'lm') +
  scale_x_continuous(limits = c(-1, 1)) +
  scale_y_continuous(limits = c(-1, 1))

```


## Model diagnostics

```{r all_residual_morans}

# extracting model weight & preparing listws for moran tests

cor_mats <- as.matrix(Initialize(cor_structs[[2]], data = usa@data))
listws <- lapply(cor_mats, mat2listw)
moran_results <- list()
m <- 1

# iterating through the models

for (mod in list(rate_mod, rate_nonres_mod, rate_res_mod,
                 rate_late_mod, rate_early_mod, prop_late_mod)) {
  
  # iterating through each year for each model
  
  for (i in 1:length(2010:2019)) {
  
    # getting the residuals for the current year
    
    this_year <- c(2010:2019)[i]
    this_listw <- listws[[i]]
    this_resid <- residuals(mod)[names(residuals(mod)) == as.character(this_year)]
    
    # now running the moran test
    
    moran_results[[m]] <- moran.mc(this_resid, 
                                   this_listw,
                                   alternative = 'two.sided',
                                   nsim = 9999)
    m <- m+1
  }
}

# putting Moran results in a nice table

do.call(rbind, lapply(moran_results, tidy)) %>% 
  mutate(across(statistic:p.value, function(x) round(x, 3))) %>% 
  mutate(year = rep(2010:2019, times = 6),
         var = rep(c('rate', 'nonres', 'res', 
                     'late', 'early', 'late_share'), each = 10),
         statistic = ifelse(p.value < 0.05, paste0(statistic, fixed('*')), statistic)) %>% 
  select(year, statistic, p.value) %>% 
  kable(booktabs = TRUE,
        #format = 'latex',
        col.names = c('Year', 'I-statistic', 'p-value'),
        caption = "Moran's I-test on model residuals",
        align = rep('c', 3)) %>% 
  pack_rows('Overall Rate', 1, 10) %>%
  pack_rows('Nonresident Rate', 11, 20) %>% 
  pack_rows('Resident Rate', 21, 30) %>% 
  pack_rows('Later-Term Rate', 31, 40) %>% 
  pack_rows('Earlier-Term Rate', 41, 50) %>% 
  pack_rows('Later-Term Share', 51, 60) %>% 
  column_spec(1:3, width = "5em") 

```

```{r resid_maps}

# I also want to map model residuals by year

states <- map_data('state')
for (y in 2010:2019) {
  p <- usa@data %>% 
    mutate(rate_resids = residuals(rate_mod),
           rate_nonres_resids = residuals(rate_nonres_mod),
           rate_res_resids = residuals(rate_res_mod),
           rate_late_resids = residuals(rate_late_mod),
           rate_early_resids = residuals(rate_early_mod),
           prop_late_resids = residuals(prop_late_mod),
           NAME_1 = str_to_lower(NAME_1)) %>% 
    inner_join(states, by = c('NAME_1' = 'region')) %>%
    filter(year == y) %>% 
    ggplot() +
    geom_polygon(aes(long, lat, group=group, fill = rate_resids),
                 color = 'black') +
    facet_wrap(~year) +
    coord_fixed(1.2) +
    labs(title = "Model residuals") +
    theme(panel.background = element_blank(),
          axis.text = element_blank(),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank())
  print(p)
}

# # making ggplot animations
# library(gganimate)
# data_resids %>%
#   ggplot() +
#   geom_polygon(aes(long, lat, group=group, fill = rate_resids),
#                color = 'black') +
#   transition_states(year) +
#   coord_fixed(1.2) +
#   labs(title = "Within-state policy scores in {closest_state}") +
#   theme(panel.background = element_blank(),
#         axis.text = element_blank(),
#         axis.line = element_blank(),
#         axis.ticks = element_blank(),
#         axis.title = element_blank())

```

```{r model_plots}

# generating diagnostic plots for each model

models <- list(rate_mod, rate_nonres_mod, rate_res_mod, 
               rate_late_mod, rate_early_mod, prop_late_mod)
outcome_vars <- c('overall rates',
                  'nonresident rate',
                  'resident rate',
                  'later-term rate',
                  'earlier-term rate',
                  'later-term share')
abbrev <- c('rate', 'nonres', 'res', 
            'late', 'early', 'prop_late')
plots <- list()
for (i in 1:length(models)) {
  
  path <- file.path(paste0('figures/eda/', abbrev[i], '_diagnostics.png'))
  
  # fitted vs residuals plot
  
  resid_vs_fit <- tibble(fit = fitted(models[[i]]), 
                       resid = residuals(models[[i]])) %>% 
  ggplot(aes(fit, resid)) +
  geom_point() +
  geom_hline(yintercept = 0,
             color = 'red',
             linetype = 'dashed') +
  theme_thesis() +
  labs(title = 'Residuals vs. fitted values',
       x = 'Fitted values',
       y = 'Residuals')
  
  # creating qqplot now
  
  plot_data <- tibble(fit = fitted(models[[i]]), 
                      resid = residuals(models[[i]])) 
  qqplot <- plot_data %>% 
    ggplot(aes(sample = resid)) +
    stat_qq() +
    stat_qq_line(col = 'red') +
    theme_thesis() +
    labs(title = 'QQ-plot for normality of residuals',
         x = 'Theoretical quantiles',
         y = 'Sample quantiles')
  
  plots[[i]] <- annotate_figure(ggarrange(resid_vs_fit, qqplot),
                                top = text_grob(paste(str_to_title(outcome_vars[[i]])),
                                                family = 'Times', size = 14))
  plots[[i]]
  ggsave(path, width = 7, height = 4)
}


```

## Spatialreg & robustness check

```{r fit_spatialreg}

# calling helper file that reads in all packages, data, and homemade functions

source('model-helpers/model_helper_spatialreg.R')

# adding our chosen model objects to the environment under easy-to-reference
# names

rate_sar <- rates_inv_dist[[2]][3][[1]]
rate_nonres_sar <- rate_nonres_inv_dist[[2]][3][[1]]
rate_res_sar <- rate_res_inv_dist[[2]][3][[1]]
rate_late_sar <- rate_late_inv_dist[[2]][3][[1]]
rate_early_sar <- rate_early_inv_dist[[2]][3][[1]]
prop_late_sar <- prop_late_inv_dist[[2]][3][[1]]


```

```{r select_spatialreg}

# getting df ready for model comparison

comparison_df <- mutate(get_model_comparisons(rates_inv_dist, rates_inv_dist2, rates_contig), 
                        var = 'rate') %>% 
  bind_rows(mutate(get_model_comparisons(rate_nonres_inv_dist, rate_nonres_inv_dist2, rate_nonres_contig), 
                   var = 'rate_nonres')) %>% 
  bind_rows(mutate(get_model_comparisons(rate_res_inv_dist, rate_res_inv_dist2, rate_res_contig),
                   var = 'rate_res')) %>% 
  bind_rows(mutate(get_model_comparisons(rate_late_inv_dist, rate_late_inv_dist2, rate_late_contig),
                   var = 'rate_late')) %>% 
  bind_rows(mutate(get_model_comparisons(rate_early_inv_dist, rate_early_inv_dist2, rate_early_contig),
                   var = 'rate_early')) %>% 
  bind_rows(mutate(get_model_comparisons(prop_late_inv_dist, prop_late_inv_dist2, prop_late_contig),
                   var = 'prop_late')) %>% 
  mutate(var = fct_relevel(var, 'rate', 'rate_nonres', 'rate_res', 
                           'rate_late', 'rate_early', 'prop_late')) %>%
    select(var, method, 
           AIC_inv_dist, AIC_inv_dist2, AIC_contig,
           BIC_inv_dist, BIC_inv_dist2, BIC_contig,
           logLik_inv_dist, logLik_inv_dist2, logLik_contig) %>% 
    arrange(var, AIC_inv_dist2) %>% 
  select(-var)

# producing a formatted table

{
  comparison_df %>% 
    mutate(across(where(is.numeric), function(x) round(x, 1))) %>% 
    kable(booktabs = TRUE,
          col.names = c('Method', 
                        rep(c('Inverse distance', 
                              'Inverse distance squared',
                              'Contiguous'),
                            times = 3)),
          align=c(rep('c', times = 10))) %>% 
    pack_rows('Overall Rate', 1, 4) %>% 
    pack_rows('Nonresident Rate', 5, 8) %>% 
    pack_rows('Resident Rate', 9, 12) %>% 
    pack_rows('Later-Term Rate', 13, 16) %>% 
    pack_rows('Earlier-Term Rate', 17, 20) %>% 
    pack_rows('Later-Term Share', 21, 24) %>% 
    add_header_above(header = c(' ' = 1, 
                                'AIC for neighborhood specification' = 3,
                                'BIC for neighborhood specification' = 3,
                                'Log-likelihood for neighborhood specification' = 3)) %>% 
    # row_spec(c(1, 5, 9), bold = T, color = "black", background = "lightyellow") %>% 
    column_spec(1:10, width = "18em") %>% 
    column_spec(seq(1, 10, by = 3), border_right = T)
}

```

```{r robustness_check_setup}

# I want to display `nlme` and `spatialreg` model coefficients all together

all_robustness_df <- mutate(get_lme_summary_df(rate_mod), dep = 'rate_mixef_nonspatial') %>% 
  bind_rows(mutate(get_lme_summary_df(rate_nonres_mod), dep = 'rate_nonres_mixef_nonspatial'),
            mutate(get_lme_summary_df(rate_res_mod), dep = 'rate_res_mixef_nonspatial'),
            mutate(get_lme_summary_df(rate_late_mod), dep = 'rate_late_mixef_nonspatial'),
            mutate(get_lme_summary_df(rate_early_mod), dep = 'rate_early_mixef_nonspatial'),
            mutate(get_lme_summary_df(prop_late_mod), dep = 'prop_late_mixef_nonspatial'),
            mutate(get_sar_summary_df(rate_sar), dep = 'rate_fixef_sar'),
            mutate(get_sar_summary_df(rate_nonres_sar), dep = 'rate_nonres_fixef_sar'),
            mutate(get_sar_summary_df(rate_res_sar), dep = 'rate_res_fixef_sar'),
            mutate(get_sar_summary_df(rate_late_sar), dep = 'rate_late_fixef_sar'),
            mutate(get_sar_summary_df(rate_early_sar), dep = 'rate_early_fixef_sar'),
            mutate(get_sar_summary_df(prop_late_sar), dep = 'prop_late_fixef_sar')) %>% 
  filter(str_detect(term, 'score')) %>% 
  mutate(value = ifelse(p_value < 0.05, paste0(round(value, 3), '*'), round(value, 3)),
         pr_z = round(p_value, 3)) %>% 
  select(term, value, dep) %>% 
  pivot_wider(names_from = dep, values_from = value) %>% 
  mutate(term = fct_relevel(term,
                            'surrounding_score', 
                            'within_score', 
                            'surrounding_score:within_score')) %>% 
  arrange(term) %>% 
  pivot_longer(2:ncol(.), names_to = 'model', values_to = 'coef') %>% 
  mutate(model = fct_relevel(model, 
                             'rate_mixef_nonspatial', 'rate_fixef_sar',
                             'rate_nonres_mixef_nonspatial', 'rate_nonres_fixef_sar',
                             'rate_res_mixef_nonspatial', 'rate_res_fixef_sar',
                             'rate_late_mixef_nonspatial', 'rate_late_fixef_sar',
                             'rate_early_mixef_nonspatial', 'rate_early_fixef_sar',
                             'prop_late_mixef_nonspatial', 'prop_late_fixef_sar'),
         var = str_replace(str_replace(model, '_mixef_nonspatial', ''), '_fixef_sar', ''),
         model = case_when(str_detect(model, 'mixef') ~ 'mixef_nonspatial',
                           str_detect(model, 'fixef') ~ 'fixef_spatial')) %>% 
  mutate(var = fct_relevel(var, 'rate', 'rate_nonres', 'rate_res',
                           'rate_late', 'rate_early', 'prop_late')) %>% 
  arrange(model) %>% 
  pivot_wider(names_from = model, values_from = coef) %>% 
  arrange(var) %>% 
  select(term, mixef_nonspatial, fixef_spatial)

# now I want to create a formatted table

all_robustness_df  %>% 
  kable(booktabs = TRUE,
        caption = paste('Robustness check of policy coefficients'),
        col.names = c(' ', 'Mixed-Effect Nonspatial Model (`nlme`)', 'Fixed-Effect SAR Model (`spatialreg`)'),
        #format = 'latex',
        align = c('l', 'c', 'c')) %>% 
  pack_rows('Overall Rate', 1, 3) %>%
  pack_rows('Nonresident Rate', 4, 6) %>% 
  pack_rows('Resident Rate', 7, 9) %>% 
  pack_rows('Later-Term Rate', 10, 12) %>% 
  pack_rows('Earlier-Term Rate', 13, 15) %>% 
  pack_rows('Later-Term Share', 16, 18) %>% 
  column_spec(1, width = "15em") %>%
  column_spec(2:3, width = '8em') 
# %>% 
#   row_spec(seq(1, 18, by = 3), bold = T, color = "black", background = "lightyellow") %>% 
#   row_spec(seq(3, 18, by = 3), bold = T, color = "black", background = "lightyellow")

```


