---
title: Policy & Abortion EDA
author: Kayla Manning
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE)

# loading libraries as needed

{
  # data cleaning tasks
  
  library(tidyverse)
  library(readxl)
  library(janitor)
  library(zoo)
  library(broom)
  library(naniar)
  library(googlesheets4)
  library(lubridate)
  
  # format tables
  
  library(reshape2)
  library(kableExtra)
  
  # for maps & plots
  
  library(maps)
  library(ggpubr)
  library(gridExtra)
  library(grid)
  
}

# individual datasets that will be useful for different visualizations

{
  # reading in gestational data that I scraped (with granular windows)

  gestation <- read_csv('data-creation/raw-data/scraped/gestational_combined.csv') %>% 
    # select(-X1) %>% 
    distinct() %>% 
    mutate(state = ifelse(state == 'New York State', 'New York', state))
  
  # reading in the raw policy data
  
  policies <- read_csv('data-creation/raw-data/clean_policies.csv')
  
  # points allotted to each level of policy

  policy_levels <- read_sheet('https://docs.google.com/spreadsheets/d/1fs9IIEJaZjr4O1pQCCNhaaMRccI4Pyg5ONC_OZ0n7Z8/edit#gid=657372929',
                        sheet = 'score_key') %>% 
    clean_names() 
  
  # looping through the different excel sheets to get the abortion count data (I
  # want the raw, uncleaned data so I can see which setates have "**" next to
  # their names, indicating missingness/nonreporting)
    
  {
    abortion_counts <- tibble()
    for (y in 2010:2019) {
      storage <- read_excel('data-creation/raw-data/downloads/abortions_2010-2019.xls', 
                            skip = 1, sheet = as.character(y)) %>% 
        select(-1) %>% 
        clean_names() %>% 
        mutate(year = y) %>% 
        rename(state = state_area) %>% 
        select(state, year, everything())
      abortion_counts <- bind_rows(abortion_counts, storage)
    }
    
    # replacing missing data with NA values

    abortion_counts <- abortion_counts %>% 
    mutate(across(everything(), function(x) na_if(x, '--')))
    
  }
}

# data with everything combined

combined <- read_csv('data-creation/raw-data/reweighted_combined_data.csv') %>% 
  mutate(within_between = fct_relevel(within_between,
                                     'low-low', 'low-med', 'low-high', 
                                     'med-low', 'med-med', 'med-high', 
                                     'high-low', 'high-med', 'high-high'))

# getting data prepared for a map

{
  library(maps)
  states <- map_data('state')
  map_df <- combined %>% 
    mutate(state = str_to_lower(state)) %>% 
    inner_join(states, by = c('state' = 'region'))
  }

# setting ggplot theme

{
  crimson <- '#dc143c'
  
  # overwriting with my own red/orange color that I think looks better (the above line
  # has the hex code from the latex template)
  
  crimson <- '#D64933'
  
  # set color schemes based on this link:
  # https://coolors.co/palette/001219-005f73-0a9396-94d2bd-e9d8a6-ee9b00-ca6702-bb3e03-ae2012-9b2226
  
  default_color <- '#A4A5AE'
  my_yellow <- '#FFE787'
  my_lightblue <- '#CDEDF6'
  within_color <- '#343F3E'
  surrounding_color <-  crimson
  overall_color <- '#023C40'
  nonres_color <- '#BA5624'
  res_color <- '#416788'
  late_color <- '#BA5624'
  early_color <- '#416788'
  prop_late_color <- '#53131E'

  # ggplot theme
  
  theme_thesis <- function() {
    theme_grey(base_family="Times") +
      theme(panel.background = element_blank(),
            axis.line = element_line(colour = 'black'))
}


}

# calling this so I can also reference my usa@data dataframe in some code

source('model-helpers/model_helper_lme.R')
  
```

# Defining variables

## Policy scores

### Raw scores

```{r score_tables}

# now I want to calculate a value to add to the hostility score based on a
# state's harshness in each area

score_key <- policy_levels %>% 
  group_by(policy) %>% 
  mutate(n_ranks = max(harsh_rank),
         score = (n_ranks-harsh_rank+1) / n_ranks) %>% 
  ungroup() %>% 
  select(-c(harsh_rank, n_ranks))

score_key %>% 
  select(-policy) %>% 
  mutate(score = round(score, 3)) %>% 
  knitr::kable(booktabs = TRUE,
               # format = 'latex',
               caption = 'Points allotted to policy levels') %>% 
  kableExtra::pack_rows(index = table(fct_inorder(score_key$policy)))

```

```{r score_visualizations}

# want to take a look at the overall distributions, with and without missingness
# starting with within-state scores

within_all <- combined %>% 
  ggplot(aes(within_score)) +
  geom_histogram(fill = default_color) +
  theme_classic(base_family="Times") +
  labs(subtitle = 'Includes all state-year observations',
       x = '', y = '')

# within_nonmissing <- combined %>% 
#   drop_na(rate_nonres, rate_late) %>% 
#   ggplot(aes(within_score)) +
#   geom_histogram() +
#   theme_classic(base_family="Times") +
#   labs(subtitle = 'Excludes states that do not report abortion data to the CDC',
#        x = 'Within-state policy score', y = '')
# 
# ggarrange(within_all, within_nonmissing,
#           nrow = 2) %>% 
#   annotate_figure(left = text_grob('Count', rot = 90, vjust = 1, 
#                                   size = 12, family = 'Times'))
# ggsave('figures/eda/reporting_groups_within_scores.png')

# also getting a plot of just the within-state scores

within_all +
  labs(x = 'Within-State Policy Score',
       y = 'Count',
       subtitle = '')
ggsave('figures/eda/within_score_hist.png',
       width = 7, height = 4)

# doing the same for surroundings

surrounding_all <- combined %>% 
  ggplot(aes(surrounding_score)) +
  geom_histogram(fill = default_color) +
  theme_classic(base_family="Times")  +
  labs(subtitle = 'Includes all state-year observations',
       x = '', y = '')
# 
# surrounding_nonmissing <- combined %>% 
#   drop_na(rate_nonres, rate_late) %>% 
#   ggplot(aes(surrounding_score)) +
#   geom_histogram() +
#   theme_classic(base_family="Times") +
#   labs(subtitle = 'Excludes states that do not report abortion data to the CDC',
#        x = 'Surrounding-state policy score', y = '')
# 
# ggarrange(surrounding_all, surrounding_nonmissing,
#           nrow = 2) %>% 
#   annotate_figure(left = text_grob('Count', rot = 90, vjust = 1, 
#                                   size = 12, family = 'Times'))
# ggsave('figures/eda/reporting_groups_surrounding_scores.png')

# also getting a plot of just the surrounding-state scores

surrounding_all +
  labs(x = 'Surrounding-State Policy Score',
       y = 'Count',
       subtitle = '')
ggsave('figures/eda/surrounding_score_hist.png',
       width = 7, height = 4)

```

```{r score_maps}

# visualizing policy scores on a map

p1 <- map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = within_score),
               color = 'black') +
  scale_fill_gradient2(high = prop_late_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Within-State\nPolicy Scores') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

# saving just the within-state map first, then adding title so I can sve the map
# with the different scores together

p1
# ggsave('figures/eda/within_map.png',
#        width = 7, height = 2)
# p1 <- p1 +
#   labs(title = 'Within-State \nPolicy Scores')

p2 <- map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = surrounding_score),
               color = 'black') +
  scale_fill_gradient2(high = surrounding_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Surrounding-State\nPolicy Scores') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
p2
# ggsave('figures/eda/surrounding_map.png',
#        width = 7, height = 2)

ggarrange(p1, p2,
          nrow = 2)
# ggsave('figures/eda/both_score_maps.png',
#        width = 7, height = 4)

```

### Tercile categories

```{r tercile_df}

# getting a table that has the cutoffs

category_cutoffs <- combined %>% 
  pivot_longer(within_score:surrounding_score) %>% 
  group_by(name) %>% 
  mutate(min = min(value),
         first_cutoff = quantile(value, 1/3),
         second_cutoff = quantile(value, 2/3),
         max = max(value)) %>% 
  select(name, min:max) %>% 
  distinct()

category_cutoffs %>% 
  kable(booktabs = TRUE,
        caption = 'Cutoffs for each score category')

```

```{r tercile_counts}

# seeing overall breakdown between the categories for reporting & all states

reporting_terciles <- combined %>% 
  drop_na(abortion_per_1k_births, rate_late) %>% 
  group_by(within_between) %>% 
  summarise(n_reporting = n())
all_terciles <- combined %>% 
  group_by(within_between) %>% 
  summarise(n_total = n())
inner_join(reporting_terciles, all_terciles) %>% 
  mutate(n_nonreporting = n_total-n_reporting) %>% 
  select(within_between, n_reporting, n_nonreporting, n_total) %>% 
  kable(caption = 'Policy terciles of reporting vs. nonreporting states',
        # format = 'latex',
        col.names = c('Tercile category', 'Reporting', 'Nonreporting', 'Total')) %>% 
  add_header_above(c(' ' = 1, 'Count of observations by CDC reporting status' = 2, ' ' = 1)) %>% 
  column_spec(4, width = '4em')

# seeing if there are repeats in a state

combined %>% 
  group_by(state) %>% 
  count(within_between) %>% 
  arrange(desc(n))
combined %>% 
  count(within_between) %>% 
  ggplot(aes(within_between, n)) +
  geom_col() +
  labs(title = 'Counts of state-year observations in each of the 9 policy categories',
       x = 'Intrastate-interstate score categories') +
  theme_classic(base_family="Times")

```

```{r tercile_viz}

# graphing the distributions of the cutoffs (side-by-side histograms of each
# score)
{
  combined %>% 
  pivot_longer(within_score:surrounding_score) %>% 
  ggplot() +
  geom_histogram(aes(value)) +
  facet_wrap(~name) +
  geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                    name == 'within_score'),
             aes(xintercept = category_cutoffs$first_cutoff[category_cutoffs$name == 'within_score']),
             color = 'red') +
  geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                    name == 'within_score'),
             aes(xintercept = category_cutoffs$second_cutoff[category_cutoffs$name == 'within_score']),
             color = 'red') +
  geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                    name == 'surrounding_score'),
             aes(xintercept = category_cutoffs$first_cutoff[category_cutoffs$name == 'surrounding_score']),
             color = 'red') +
  geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                    name == 'surrounding_score'),
             aes(xintercept = category_cutoffs$second_cutoff[category_cutoffs$name == 'surrounding_score']),
             color = 'red') +
  theme_classic(base_family="Times") +
  labs(title = 'Cutoffs for policy score categories',
       subtitle = 'Based on terciles of the score distributions')
}

# visualizing on 2d plot (scatterplot with intrastate on x and interstate on y)
{
  combined %>% 
    pivot_longer(within_score:surrounding_score) %>% 
    group_by(name) %>% 
    mutate(first_cutoff = quantile(value, 1/3),
           second_cutoff = quantile(value, 2/3)) %>% 
    mutate(level = case_when(value <= first_cutoff ~ 'low',
                             value > first_cutoff & value <= second_cutoff ~ 'med',
                             value > second_cutoff ~ 'high')) %>% 
    select(-c(first_cutoff, second_cutoff)) %>% 
    group_by(state, year) %>% 
    mutate(score_type = name) %>% 
    pivot_wider(names_from = name, values_from = level) %>% 
    pivot_wider(names_from = score_type, values_from = value, names_prefix = 'score') %>% 
    mutate(across(c(surrounding_score, scoresurrounding_score),
                  function(x) na.locf(x, fromLast = TRUE))) %>% 
    mutate(across(c(within_score, scorewithin_score),
                  function(x) na.locf(x))) %>% 
    mutate(within_between = paste(within_score, surrounding_score, sep = '-')) %>% 
    select(-c(within_score, surrounding_score)) %>% 
    rename(surrounding_score = scoresurrounding_score,
           within_score = scorewithin_score) %>% 
    ggplot(aes(within_score, surrounding_score, color = fct_relevel(within_between,
                                        levels = c('low-low', 'low-med', 'low-high',
                                                   'med-low', 'med-med', 'med-high',
                                                   'high-low', 'high-med', 'high-high')))) +
    geom_point() +
    geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                      name == 'within_score'),
               aes(xintercept = category_cutoffs$first_cutoff[category_cutoffs$name == 'within_score']),
               color = 'red') +
    geom_vline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                      name == 'within_score'),
               aes(xintercept = category_cutoffs$second_cutoff[category_cutoffs$name == 'within_score']),
               color = 'red') +
    geom_hline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                      name == 'surrounding_score'),
               aes(yintercept = category_cutoffs$first_cutoff[category_cutoffs$name == 'surrounding_score']),
               color = 'red')+
    geom_hline(data = filter(pivot_longer(combined, within_score:surrounding_score),
                      name == 'surrounding_score'),
               aes(yintercept = category_cutoffs$second_cutoff[category_cutoffs$name == 'surrounding_score']),
               color = 'red') +
    theme_thesis() +
    labs(color = '[Within]-[Surrounding]',
         x = 'Within-State Policy Score',
         y = 'Surrounding-State Policy Score') +
    scale_color_brewer(palette = 'OrRd')
}
ggsave('figures/eda/tercile_grid.png', height = 4, width = 7)

# seeing how categories change over time

combined %>% 
  select(within_between, year) %>% 
  ggplot(aes(within_between)) +
  geom_bar() +
  facet_wrap(~year)+
  coord_flip() +
  labs(x = 'Policy Category',
       y = 'Count') +
  theme_thesis()
ggsave('figures/eda/terciles_time.png', height = 6, width = 7)

```

```{r explore_policy_levels}

# getting counts of different policy types over the years... showing 10 that had
# the largest magnitudes of change over the period from 2010-2019

policies %>% 
  select(-c(state, as_of, accessed)) %>% 
  group_by(year, policy, level) %>% 
  summarize(n = n(), .groups = 'drop') %>% 
  filter(year %in% 2010:2019) %>% 
  pivot_wider(names_from = year, values_from = n) %>% 
  mutate(across(3:ncol(.), function(x) replace_na(x, 0))) %>% 
  arrange(desc(abs(`2019`-`2010`)))

# getting a count of most popular policy levels when aggregated across all
# states and years

policies %>% 
  select(-c(state, as_of, accessed)) %>% 
  group_by(policy, level) %>% 
  summarize(n = n(), .groups = 'drop') %>% 
  drop_na(level) %>% 
  arrange(desc(n)) %>% head(10)

```

## Dependent variables

```{r rates}

# visualizing abortion rates per population & births... highly correlated. for
# substantive reasons (since birth counts include non-residents & my question
# has to do with abortions as a function of births rather than a function of
# residents) & to control for female population, I will do abortions per births

combined %>% 
  ggplot(aes(abortion_per_1k_births, abortion_per_100k_pop)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  theme_classic(base_family="Times") +
  labs(title = 'Abortion rates as a function of population vs total births',
       subtitle = 
         paste('Correlation of', round(cor(abortion_rates$abortion_per_100k_pop,
                                           abortion_rates$abortion_per_1k_births,
                                           use = 'complete.obs'), 3)))

# plotting histograms of the two rates

combined %>% 
  select(abortion_per_100k_pop, abortion_per_1k_births) %>% 
  pivot_longer(everything()) %>% 
  ggplot(aes(value)) +
  geom_histogram() +
  facet_wrap(~name) +
  labs(title = 'Nearly identical distributions for different abortion rate definitions',
       subtitle = 'Main analysis will focus on abortions as a rate of births') +
  theme_classic(base_family="Times")

# getting extreme values

usa@data %>% 
  drop_na(abortion_per_1k_births) %>% 
  filter(abortion_per_1k_births %in% c(min(abortion_per_1k_births), 
                                       max(abortion_per_1k_births))) %>% 
  select(NAME_1, year, abortion_per_1k_births, rate_nonres, rate_res)

# mapping

 map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = abortion_per_1k_births),
               color = 'black') +
  scale_fill_gradient2(high = overall_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Abortions per \n1000 live births') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/overall_rate_map.png', 
        width = 7, height = 2)

```

```{r nonres_and_res_rate}

# taking a look at the histogram... incredibly skewed

combined %>% 
  ggplot(aes(rate_nonres)) +
    geom_histogram() +
    labs(title = 'Nonresident abortion rate') +
    theme_classic(base_family="Times")

# getting extreme values for nonresidents

usa@data %>% 
  drop_na(rate_nonres) %>% 
  filter(rate_nonres %in% c(min(rate_nonres), max(rate_nonres))) %>% 
  select(NAME_1, year, rate_nonres)

# doing the same for residents

usa@data %>% 
  drop_na(rate_res) %>% 
  filter(rate_res %in% c(min(rate_res), max(rate_res))) %>% 
  select(NAME_1, year, rate_res)

# mapping, nonresidents first

map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = rate_nonres),
               color = 'black') +
  scale_fill_gradient2(high = nonres_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Nonresident abortions \nper 1000 live births') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/nonres_rate_map.png', 
        width = 7, height = 2)
 
 # repeating for resident abortion rate
 
 map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = rate_res),
               color = 'black') +
  scale_fill_gradient2(high = res_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Resident abortions \nper 1000 live births') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/res_rate_map.png', 
        width = 7, height = 2)

```

```{r late_vs_early}

# generating plot and getting summary stats

combined %>% 
  ggplot(aes(prop_late)) +
  geom_histogram() +
  labs(title = 'Distribution of later-term share of abortions') +
  theme_classic(base_family="Times")

# getting later-term rate extreme values

usa@data %>% 
  drop_na(rate_late) %>% 
  filter(rate_late %in% c(min(rate_late), max(rate_late))) %>% 
  select(NAME_1, year, rate_late)

# getting earlier-term rate extreme values

usa@data %>% 
  drop_na(rate_early) %>% 
  filter(rate_early %in% c(min(rate_early), max(rate_early))) %>% 
  select(NAME_1, year, rate_early)

# getting later-term share extreme values

combined %>% 
  drop_na(prop_late) %>% 
  filter(prop_late %in% c(min(prop_late), max(prop_late))) %>% 
  select(state, year, prop_late)

```

```{r timing_maps}

# mapping later-term abortion rates

 map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = rate_late),
               color = 'black') +
  scale_fill_gradient2(high = late_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Later-term abortions \nper 1000 live births') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/late_rate_map.png', 
        width = 7, height = 2)
 
 # mapping earlier-term abortion rates

 map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = rate_early),
               color = 'black') +
  scale_fill_gradient2(high = early_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Earlier-term abortions \nper 1000 live births') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/early_rate_map.png', 
        width = 7, height = 2)
 
# now looking at the later-term share of abortions
 
map_df %>% 
  filter(year %in% c(2010, 2019)) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = prop_late),
               color = 'black') +
  scale_fill_gradient2(high = prop_late_color) +
  coord_fixed(1.2) +
  facet_wrap(~year, nrow = 1) +
  labs(fill = 'Later-term share \nof abortions') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
 ggsave('figures/eda/late_share_map.png', 
        width = 7, height = 2)

```

```{r combine_dep_vars}

# # getting simple correlation between all of the variables
# 
# combined %>% 
#   select(rate_nonres, rate_res, , rate_late, rate_early, prop_late, 
#          abortion_per_1k_births, 
#          abortion_per_100k_pop) %>% 
#   cor(use = 'complete.obs') %>% 
#   kable(booktabs = TRUE,
#         caption = 'Bivariate correlations between dependent variables')
# combined %>% 
#   select(rate_nonres, rate_res, , rate_late, rate_early, prop_late, 
#          abortion_per_1k_births, 
#          abortion_per_100k_pop) %>% 
#   filter_at(vars(rate_nonres, rate_res, , rate_late, rate_early, prop_late, 
#          abortion_per_1k_births, 
#          abortion_per_100k_pop), 
#          all_vars(!is.na(.))) %>% 
#   cor() %>% 
#   ggcorrplot::ggcorrplot(hc.order = TRUE, type = "lower",
#    lab = TRUE)
# 
# # generating histograms of all of the distributions
# 
# combined %>% 
#   select(rate_nonres, rate_res, , rate_late, rate_early, prop_late, 
#          abortion_per_1k_births, 
#          abortion_per_100k_pop)%>% 
#   pivot_longer(everything()) %>% 
#   ggplot(aes(value)) +
#   geom_histogram() +
#   facet_wrap(~name, scales = 'free') +
#   theme_classic(base_family="Times") +
#   labs(title = 'Distributions of outcome variables')

# mapping combined values

```

## Limitations

### Missing abortion data

#### Missing abortion counts

```{r missing_state_yrs_abortions}

# want to get a list of years in which they didn't report... I should exclude
# these states from the analysis because they wouldn't have actually had 0
# abortions... it is an issue that CA didn't report though because they would
# likely have a high number since they're very democratic

nonreporting_states <- c('California', 'Florida', 'Maryland', 'New Hampshire')
nonreport_years_df <- abortion_counts %>% 
  filter(str_detect(state, fixed('**'))) %>% 
  select(state, year) %>% 
  group_by(state) %>% 
  summarise(years = list(unique(year)))

missing_states <- sapply(nonreport_years_df$state, 
       function (x) str_replace_all(str_to_lower(str_remove_all(x, 
                                                                fixed('*'))), 
                                    ' ', '_'))

# getting a vector of each year that the data is missing for the respective state

{
  i <- 1
  for (state in missing_states) {
    vector_name <- paste0('missingyrs_', state)
    assign(vector_name, nonreport_years_df$years[i][[1]])
    i <- i+1
  }
}

# I will want to put this info in a table

missing_state_yr_table <- tibble()
for (i in 1:length(missing_states)) {
  this_state <- cbind(rep(missing_states[i], length(nonreport_years_df$years[[i]])),
      nonreport_years_df$years[[i]]) %>% 
  as.data.frame()
  missing_state_yr_table <- rbind(missing_state_yr_table, this_state)
}

# # getting states that didn't report to the CDC for which I obtained data from
# # the Guttmacher APC
# 
# apc_extra_data <- abortion_long %>% 
#   distinct(state_location, year) %>% 
#   count(state_location) %>% 
#   filter(n < 10,
#          !str_detect(state_location, fixed('*')),
#          !str_detect(state_location, 'District of')) %>% 
#   inner_join(abortion_long) %>% 
#   filter(str_detect(state_residence, 'Total')) %>% 
#   drop_na(count) %>% 
#   select(-n)

# formatting the table

missing_state_yr_table %>% 
  rename(state = V1, year = V2)  %>% 
  mutate(state = str_replace(str_to_title(str_replace_all(state, '_', ' ')),
                             ' Of ', ' of '),
         year = as.numeric(year)) %>%
  # anti_join(apc_extra_data, by = c('state' = 'state_location', 'year')) %>% 
  dcast(state ~ year) %>% 
  mutate(across(2:ncol(.), function(x) ifelse(is.na(x), '', 'X'))) %>% 
  filter(state != 'District of Columbia') %>% 
  rename(State = state) %>% 
  select(State:`2019`) %>% 
  kable(caption = 'State-year observations missing abortion count data',
        # format = 'latex',
        booktabs = TRUE)

```

#### Missing gestational data

```{r missing_gestation_breakdown}

# reading in data that lists the state-year observations that did not report any
# gestation data

nonreport_gestation <- read_excel('data-creation/raw-data/helper/nonreport_gestation.xlsx')

# getting states that are only missing certain years & states that are missing
# all years (for future reference when comparing different subsets of
# missingness)

missing_some_gestation <- nonreport_gestation %>% 
  count(state) %>% 
  filter(n < 10) %>% 
  pull(state)
missing_all_gestation <- nonreport_gestation %>% 
  count(state) %>% 
  filter(n == 10) %>% 
  pull(state)

# creating table for all missing

missing_all_df <- tibble(state = rep(missing_all_gestation, each = length(2007:2019)),
       year = rep(2007:2019, times = length(missing_all_gestation))) %>% 
  dcast(state ~ year) %>% 
  mutate(across(`2007`:`2019`, function(x) ifelse(is.na(x), '', 'X')))

# creating table for some missing & then joining

nonreport_gestation %>% 
  dcast(state ~ year) %>% 
  mutate(across(`2010`:`2019`, function(x) ifelse(is.na(x), '', 'X'))) %>% 
  arrange(state) %>% 
  rename(State = state) %>% 
  kable(caption = 'States that do not report gestational data to CDC',
        format = 'latex',
        booktabs = TRUE)

```

```{r make_missing_tables}

# first I'm getting state-year observations that do not report gestational
# data... this may include states that also fail to report abortion count data

data_by_nonreport_gestation <- combined %>% 
  right_join(nonreport_gestation, by = c('state' = 'state', 'year')) %>% 
  filter(is.na(pre13)) %>% 
  mutate(nonreport_gestation = TRUE)

# now I'm getting data & coding state-year observations for (a) whether the
# STATE is missing some gestational data FOR ANY YEAR in the timeframe (rather
# than state-year observation), (b) whether a state-year observation is missing
# abortion counts for that year, or (c) if a state is not missing any
# gestational data across any of the years OR abortion count data for that given
# year

data_by_missingness <- combined %>% 
  left_join(gestation, by = c('state', 'year')) %>% 
  full_join(data_by_nonreport_gestation) %>% 
  mutate(nonreport = case_when(is.na(abortion_per_1k_births) ~ 'nonreport_abortions',
                               nonreport_gestation ~ 'nonreport_gestation',
                               TRUE ~ 'report_all')) %>% 
  mutate(nonreport = ifelse(nonreport != 'report_all', T, F)) %>% 
  filter(!state %in% c('District of Columbia', 'Hawaii', 'Alaska'),
         !str_detect(state, 'Total')) %>% 
  select(-c(state:births, abortion_per_100k_pop:post13, 
            within_between, x0_13:nonreport_gestation))

missing_balance_check <-  data_by_missingness %>% 
  group_by(nonreport) %>% 
  summarise_all(function(x) mean(x, na.rm = TRUE)) %>% 
  pivot_longer(2:ncol(.), names_to = 'statistic', values_to = 'mean') %>% 
  filter(statistic != '...1') 

# getting list of states in each category

state_nonreport_cats <- combined %>% 
  distinct() %>% 
  mutate(report_all = !is.na(abortion_per_1k_births) & !is.na(rate_late))

# making a map that is shaded by the percentage of years in which it reports

state_nonreport_cats %>% 
  group_by(state) %>% 
  summarize(report_years = sum(report_all)) %>% 
  mutate(state = str_to_lower(state),
         years_reporting = case_when(report_years == 10 ~ 'All',
                             report_years == 0 ~ 'None',
                             TRUE ~ 'Some')) %>% 
  inner_join(states, by = c('state' = 'region')) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = years_reporting),
               color = 'black') +
  scale_fill_manual(breaks = c('All', 'Some', 'None'),
                    values = c(early_color, my_lightblue, default_color)) +
  coord_fixed(1.2) +
  labs(fill = 'Years reported, \n2010-2019') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
ggsave('figures/eda/nonreport_map.png', width = 7, height = 2)

# getting a table with the number of observations in each category

combined %>% 
  left_join(gestation, by = c('state' = 'state', 'year')) %>% 
  full_join(data_by_nonreport_gestation) %>% 
  mutate(nonreport = !(!is.na(abortion_per_1k_births) & !is.na(rate_late))) %>% 
  select(state, year, nonreport) %>% 
  filter(!state %in% c('District of Columbia', 'Hawaii', 'Alaska'),
         !str_detect(state, 'Total')) %>%
  distinct() %>% 
  group_by(nonreport) %>% 
  count() %>% 
  mutate(nonreport = case_when(nonreport ~ 'Yes',
                               !nonreport ~ 'No')) %>% 
  kable(booktabs = TRUE,
        caption = 'Number of observations in each missingness category',
        format = 'latex',
        col.names = c('Missing CDC data', 'Number of observations')) 

```

```{r missing_balance}

# comparing sample statistics for missing/non-missing groups & viewing alongside
# missing abortion

options(scipen = 999)

# balance check for control variables

# missing_balance_check %>% 
#   filter(!statistic %in% c('abortion_per_1k_births',
#                            'rate_nonres',
#                            'rate_res',
#                            'rate_late',
#                            'rate_early',
#                            'prop_late',
#                            'prop_nonres'),
#          !str_detect(statistic, 'score')) %>% 
#   ggplot(aes(nonreport, mean)) +
#   geom_col() +
#   facet_wrap(~statistic, scales = 'free') +
#   coord_flip() +
#   labs(title = 'Examining control variables of missingness categories',
#        subtitle = 'Median value for each variable within each category', 
#        x = '') +
#   theme_classic(base_family="Times")

# printing out a table with the mean values for each group and p-value for
# analysis of variance

options(scipen = 999)
missing_balance_check %>% 
  mutate(nonreport = ifelse(nonreport, 'Nonreporting', 'Reporting')) %>% 
  pivot_wider(names_from = nonreport, values_from = mean) %>% 
  filter(!statistic %in% c('abortion_per_1k_births',
                           'rate_nonres',
                           'rate_res',
                           'rate_late',
                           'rate_early',
                           'prop_late',
                           'prop_nonres')) %>% 
  mutate(pvalue = c(tidy(t.test(within_score ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(surrounding_score ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(dem_2party ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(hh_income ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(prop_bachelors ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(total_population ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(prop_hisp ~ nonreport, 
                             data = data_by_missingness))$p.value[1],
                    tidy(t.test(prop_nonwhite ~ nonreport, 
                             data = data_by_missingness))$p.value[1])) %>% 
  mutate(across(is.numeric, function(x) ifelse(x < 100, round(x, 3), round(x, 0)))) %>% 
  mutate(statistic = fct_relevel(statistic, 'within_score', 'surrounding_score')) %>% 
  arrange(statistic, desc(pvalue)) %>% 
  kable(booktabs = TRUE,
        caption = 'Two-sided t-test for difference in means',
        format = 'latex',
        col.names = c(' ', 'Reporting', 'Nonreporting', 'p-value'),
        escape = FALSE) %>% 
  pack_rows('Policy scores', 1, 2) %>% 
  pack_rows('Control variables', 3, 8) %>% 
  column_spec(2:4, '8em') %>%
  add_header_above(c(' ' = 1, 'CDC Reporting Status' = 2, ' ' = 1))

```

### Issues with policy data

#### Policy timelines

```{r policy_dates}

# printing as-of dates for my policy years

asofdf <- policies %>% 
  select(year, as_of) %>% 
  filter(year %in% 2010:2019) %>% 
  distinct() %>% 
  mutate(as_of = paste(month(as_of, label = TRUE, abbr = FALSE), day(as_of))) 

asofdf %>% 
  rename(Year = year, `Earliest available policies` = as_of) %>% 
  kable(booktabs = TRUE,
        format = 'latex',
        caption = 'Earliest available policy data on the Internet Archive')

```

#### Enjoined policies

```{r policy_counts}

# seeing how many enjoined policies there are... partial birth ban isn't really
# considered harsh since it's a very common ban on late term pregnancies, so I
# think it's okay to exclude enjoined observations... in addition, previous work
# by Blum et al. found that a parental notification statute passed with judicial
# bypass procedures had little impact on decision-making of minors obtaining
# abortions (i.e. I don't think having an enjoined policy, through a similar
# legal loophole, would be much different but I should consult with Henry or
# someone else about that once I get to writing)

policies %>% 
  select(-c(state, as_of, accessed)) %>% 
  filter(level == 'Enjoined') %>% 
  group_by(policy, level) %>% 
  summarize(n = n(), .groups = 'drop') %>% 
  arrange(desc(n)) %>%
  select(-level) %>% 
  kable(booktabs = TRUE,
        col.names = c('Policy', 'Count'),
        # format = 'latex',
        caption = 'State-Year Observations with Injunctions for Each Policy')

```

### Post-Dobbs & Miscellaneous

```{r policy_descriptions}

# reading in variable descriptions from Google sheet I created

descriptions <- read_sheet('https://docs.google.com/spreadsheets/d/1fs9IIEJaZjr4O1pQCCNhaaMRccI4Pyg5ONC_OZ0n7Z8/edit#gid=1363159999',
           sheet = 'variable_names')

# formatting into a kable for latex

descriptions %>% 
  kable(booktabs = TRUE,
        #format = 'latex',
        caption = 'Guttmacher Policy Variables and Meaning')

```

```{r sept2022_policies}

# sourced from https://reproductiverights.org/maps/abortion-laws-by-state/ on
# 10/1/2022

sept2022 <- googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/10Ew2A-PgFMNV4UcnaGxAmzHKkWdfYIu4E6VK98yCJNk/edit#gid=0') %>% 
  mutate(State = tolower(State)) %>% 
  inner_join(states, by = c('State' = 'region'))
library(scales)
sept2022 %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, fill = Policy),
               color = 'black') +
  coord_fixed(1.2) +
  scale_fill_manual(breaks = c('Expanded Access',
                               'Protected',
                               'Not Protected',
                               'Hostile',
                               'Illegal'),
                    values = c('#416788',
                               '#CDEDF6',
                               '#FFE787',
                               '#D64933',
                               '#53131E')) +
  labs(fill = '') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

ggsave('figures/eda/dobbs_map.png',
       width = 7, height = 2)

```

```{r clinics2017}

# mapping 2017 clinics and I want to see its correspondence to missingness (it's
# the percentage of counties within a state that don't have any clinics)

clinics <- read_sheet('https://docs.google.com/spreadsheets/d/1fs9IIEJaZjr4O1pQCCNhaaMRccI4Pyg5ONC_OZ0n7Z8/edit#gid=1548077489', sheet = 'clinics')

clinics %>% 
  mutate(state = tolower(state)) %>% 
  left_join(states, by = c('state' = 'region')) %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = pct_without_clinic),
               color = 'black') +
  scale_fill_gradient2(high = crimson) +
  coord_fixed(1.2) +
  labs(fill = 'Counties Without an \nAbortion Clinic (%)') +
  theme_grey(base_family = 'Times') +
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
ggsave('figures/eda/clinic_map.png',
       width = 7, height = 3)

clinics %>% 
  mutate(report = ifelse(state %in% usa@data$NAME_1, 'Reporting', 'Nonreporting')) %>% 
  ggplot(aes(report, pct_without_clinic)) +
  geom_boxplot(fill = crimson) +
  theme_thesis() +
  labs(x = 'CDC Reporting Status',
       y = 'Counties Without an Abortion Clinic (%)')
ggsave('figures/eda/clinic_boxplot.png',
       width = 6, height = 4)

clinics %>% 
  mutate(nonreport = ifelse(!state %in% usa@data$NAME_1, 1, 0)) %>% 
  select(pct_without_clinic, report)

```

